sudo: required

language: scala

scala:
  - 2.11.8
  - 2.12.1

services:
  - docker
  - postgresql

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2

addons:
  postgresql: "9.4"

script:
  - sbt compile
  - sbt coverage test

after_success:
  - sbt coverageReport coveralls

